# -*- coding: utf-8 -*-
"""19th_Augest_Python_Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9LgVMDgA2qOG_oRFp2mysweBjIJVrge
"""

#A program to swap the value of two variable without usning temp variable

#We are taking two variables x,y and assigning them value by taking user input .
x=input("enter 1st number")
y=input("enter 2nd number ")
print("Values before swapping are:" ,x , y)
x= int(x)+int(y)
y= int(x)-int(y)
x= int(x)-int(y)
print("Value after swapping are :",x,y)

#Area of a rectangle

l=input("Enter the lenght of the rectangle : ")
w=input("enter the width of the rectangle : ")
area=int(l)*int(w)
print("The area of the Rectangle is :",area)

#celcius to Fahernhiet

celsius=input("Enter the Temperature in Celsius : ")
f=(int(celsius)*(9/5)+32)
print("Temperature in Fahernheit is :" ,f)

#length of a string

x=input("enter a string : ")
y=len(x)
print("The lenght of the string is :",y)

#Vowel check counter

x=input("enter a Sentance : ") #Taking user input of the sentance
count=0 #a genral counter variable to count the no of vowels
y=x.lower() #converting the whole sentance into Lowercase so that we don't have to check for Upper cases Vowels also .
for i in y:  #itterating through the sentance and checking each charater for vowel check
  if i=='a' or i=='e' or i=='i' or i=='o'or i=='u':
    count=count+1
if count > 0:
  print("This sentance has some vowels and the no of vowels are :" ,count)
else:
  print("Vowels not found ")

#Reverse the string using string slicing

x=input("enter a Sentance : ") #Taking user input of the sentance
y=len(x) #Finding the length of the string/sentance
y=y+1 #making the length+1 so that we can ittrate till 1st character(as we are using slicing menthod to itterate from reverse)
print("Reversed string is :",x[-1:-y:-1])

#String Palindrome

x=input("enter a Sentance : ") #Taking user input of the sentance
x=x.lower() #converting it to smallercase just in case user enters a uppercase charter and in palindrome check it fails just cuz of Uppercase/lowercase mismatch
y=len(x) #Finding the length of the string/sentance
y=y+1 #making the length+1 so that we can ittrate till 1st character(as we are using slicing menthod to itterate from reverse)
z=x[-1:-y:-1]
if(z==x):
  print("palindrome")
else:
  print("Not a Plaindrome")

#Removing spaces from string

x=input("enter a String : ")
y=x.replace(" ","")
print(y)